### ISSUE TITLE
accuracy of Dense Net is lower than accuracy in your paper

### ISSUE THREAD

**Issue by ducanh841988** [JianshuZhang/WAP#11]
Hi Jianshu! I retrain Dense Net Decoder. I got 17% of WER and 44% of Exp Rate on validation and 17.05 WER and 42.6% of Exp Rate on Testing set (CROHME 2014 test set). It is lower than accuracy in your paper. Is this version same with the version of your paper? I want to get the same accuracy as in your paper, could you give me advises?
Thank a lot.
Anh

**Comment by JianshuZhang** [comment]
Hi, good to see you! The result presented in my paper is an ensemble of 5 models. You can try that, I believe your result is just a single model.

**Comment by ducanh841988** [comment]
Thank you for your quick answer. 
Is it consistent with a single model in your experiment?
I will try your model with my data generation.
Thank you.

**Comment by JianshuZhang** [comment]
Yes. This is my source code.

发自我的 iPhone
