### ISSUE TITLE
Missing image in training set?

### ISSUE THREAD

**Issue by masoncusack** [JianshuZhang/WAP#13]
Hi Jianshu,

Your paper says there are 8836 expressions in the training set, but the dataset you provide has 8835. I would not expect this to make a huge difference but am trying to match your results exactly.

Mason

**Comment by JianshuZhang** [comment]
Yes, my provided dataset only contains 8835 expressions because one training inkml file provided by CROHME is wrong, no useful inks. And, as you said, the difference is trivial and my experiments actually used 8835 expressions.
