### ISSUE TITLE
Where is 'offline-train.pkl'?

### ISSUE THREAD

**Issue by sjwang222** [JianshuZhang/WAP#15]
Hi, Jianshu

Recently I have been pursuing your paper and trying to reproduce your results by your codes. However when i try 
'bash train.sh'
Python replies that 
'Traceback (most recent call last):
  File "./train_nmt_weightnoise.py", line 86, in <module>
    'reload': [True]})
  File "./train_nmt_weightnoise.py", line 46, in main
    use_dropout=params['use-dropout'][0])
  File "/root/WAP-master/VGG/nmt_weightnoise.py", line 1067, in train
    batch_size=batch_size, batch_Imagesize=batch_Imagesize,maxlen=maxlen,maxImagesize=maxImagesize)
  File "/root/WAP-master/VGG/data_iterator.py", line 14, in dataIterator
    fp=open(feature_file,'rb')
IOError: [Errno 2] No such file or directory: '../data/offline-train.pkl''

So what is exactly 'offline-trian.pkl'? and where can i get such a file?

Thanks!

**Comment by JianshuZhang** [comment]
You should first run WAP/data/gen_pkl.py to generate the data, you may also need to change the path.

**Comment by sjwang222** [comment]
Thanks! It works. Would you like to recommend the server configurations (especially GPUs)  you used to train this network? and how much time the training process will take? Thanks!

**Comment by JianshuZhang** [comment]
Telsa M40, it may takes about 100 epoches, nearly 24 hours

**Comment by sjwang222** [comment]
Thanks for your reply~

**Comment by sjwang222** [comment]
We tried to reproduce the results. After training for 24 hours, the process stopped with bad-counter achieve 15 three times while test accuracy achieved at 28%. Should we turn on the 'reload' option to start training based on pre-trained params to get a better result?

**Comment by JianshuZhang** [comment]
I guess you use the VGG encoder, I suggest you to try the DenseNet encoder, the VGG encoder is hard to train, we need to change the dropout and employ weightnoise.

**Comment by sjwang222** [comment]
Thank you for your clarifications and DenseNet worked perfectly! Sorry for the very very late response... I thought I have replied upon receiving your comments ... :)
