### ISSUE TITLE
question about beamsearch

### ISSUE THREAD

**Issue by Zhang-O** [JianshuZhang/WAP#27]
line 72 in translate.py 
cand_scores = hyp_scores[:, None] - numpy.log((next_p))

I think here should be hyp_scores[:, None] * next_p.
The probabilities should be computed in multiplication with time step.
Is there anything I overlooked?

**Comment by JianshuZhang** [comment]
Yes, the probabilities should be computed in multiplication, but log(a*b) = log(a)+log(b), so here I use the log domain to compute.

**Comment by Zhang-O** [comment]
en, it is 
min( - numpy.log(next_p(t-1))  - numpy.log(next_p(t)) ) 
= min( -numpy.log(next_p(t-1) * next_p(t)) )
=- max( numpy.log(next_p(t-1) * next_p(t)) )

**Comment by Zhang-O** [comment]
thanks!
