### ISSUE TITLE
Question about gen_sample function

### ISSUE THREAD

**Issue by wwjwhen** [JianshuZhang/WAP#4]
Hi, jianshu, in your WAP/Densenet codes, there is a gen_sample() function, and it is used to generate predicted latex formula given an input image x. I have struggled to read through the lines, yet fail to get total insight of the codes, is it just a greedy algorithm to gather max-probability vocabulary at each time step or it contains some other tricks?  BTW, could you add more comments to gen_sample function, I think that will make your codes much easier to read :), thank you

**Comment by JianshuZhang** [comment]
The main body of gen_sample function is the beam search algorithm, which is used to find a max-probability string. As for detailed instructions about beam search algorithm, I recommend Section 6.2.1 in 'K. Cho, Natural language understanding with distributed representation'

**Comment by wwjwhen** [comment]
It's nice of you to always reply promptly, I think now I get it,  and thanks for your recommendation!
