### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tirinox** [JianshuZhang/WAP#5]
Thank you for providing those great source codes. 
But I'm experiencing many difficulties running it.
Could you please add more detailed step-by-step instructions how to run it?

**Comment by JianshuZhang** [comment]
After preparing the training data and testing data, the source codes can be run by 'bash run.sh'.
The source codes can be run well on 24G GPU, if your GPU is 12G, then reduce the batch_Imagesize from 500000 to 400000, I will add this description later.
If you have more difficulties, you can show me the error and I will try to answer it as soon as possible.

**Comment by wwjwhen** [comment]
@tirinox 
jianshu's codes can run on pygpu 0.6.9 and theano 0.9.0 as alternative

**Comment by SJTUStevenDu** [comment]
@JianshuZhang I couldn't find the file 'run.sh'. And when I run 'bash train.sh', it keeps telling me that 

File "WAP/VGG/nmt.py", line 4, in <module>
    import theano
ImportError: No module named theano

But if I run python and 'import theano' directly, I can import theano. 
Could you please provide more detailed instructions? Thank you a lot.
