### ISSUE TITLE
Question about the ensemble method in the code

### ISSUE THREAD

**Issue by SuperHan777** [JianshuZhang/WAP#7]
Hi Jianshu! I have read your paper(it's a great job), and I have also run your code in my GPU(GTX 1080Ti). But I only achieved 42% recognition rate using the densenet. Your paper says that you use 5 models to get a better result(50%), I'm wondering if your released code has implemented the ensemble method?

**Comment by JianshuZhang** [comment]
The ensemble codes will be released in soon future, waiting for the notification of another paper's submission

**Comment by SuperHan777** [comment]
Is it normal for me to use one model to get 42% recognition rate? Is the ensemble method makes such a great improvement?

**Comment by JianshuZhang** [comment]
single model achieves about 44-45% ExpRate. You can try training 5 models to see the average performance.



xysszjs@mail.ustc.edu.cn
 
From: SuperHan777
Date: 2018-05-07 14:26
To: JianshuZhang/WAP
CC: Jianshu Zhang; Comment
Subject: Re: [JianshuZhang/WAP] Question about the ensemble method in the code (#7)
Is it normal for me to use one model to get 42% recognition rate? Is the ensemble method makes such a great improvement?

**Comment by SuperHan777** [comment]
Thanks!

**Comment by SuperHan777** [comment]
Hi Jianshu!
I have read your DenseNet code and paper recently. It seems that the code doesn't contain the multi-scale attention branch. I'm not very sure about this, could you tell me? thanks!

**Comment by JianshuZhang** [comment]
Yes, only single-scale attention branch. The paper was recently accpeted, we didn't release the code yet. We will release the multi-scale code in soon future.



xysszjs@mail.ustc.edu.cn
 
From: SuperHan777
Date: 2018-05-11 17:02
To: JianshuZhang/WAP
CC: Jianshu Zhang; Comment
Subject: Re: [JianshuZhang/WAP] Question about the ensemble method in the code (#7)
Hi Jianshu!
I have read your DenseNet code and paper recently. It seems that the code doesn't contain the multi-scale attention branch. I'm not very sure about this, could you tell me? thanks!
