### ISSUE TITLE
Question about validation set

### ISSUE THREAD

**Issue by wwjwhen** [JianshuZhang/WAP#8]
Hi ,jianshu, Could I know where can I get validation set i.e. 2013 test? The validation set is not attached in your project.

**Comment by JianshuZhang** [comment]
It could be found on CROHME 2016 website, i.e. http://ivc.univ-nantes.fr/CROHME/

**Comment by wwjwhen** [comment]
OK, I have gone through the website and dumped the data, but I find that the images you provided are not the same size of what the inkml Viewer produced as officially given in http://saskatoon.cs.rit.edu/inkml_viewer/, so the scale of the pictures are different, I wonder how do you convert your inkml file into bmp pictures?

**Comment by JianshuZhang** [comment]
Yes, converting inkml files into bmp pictures need some normalization, while these codes are provided by iFLYTEK company when I was intern, so I am not sure whether I can release these codes. But I believe I could tell you that the normalization needs bilinear interpolation, and the average size of each math symbol is normalized to 40 pixels (short length, keeping the ratio of height to width)

**Comment by wwjwhen** [comment]
Nice and prompt reply! Looking forward to the original codes, yet your tips already enlighten me!

**Comment by wwjwhen** [comment]
In fact, instead of releasing the codes, you can release the 2013test images, then your project would be perfect

**Comment by JianshuZhang** [comment]
Yes, indeed. But the latex notations of CROHME 2013 has not been well normalized, we only generate some rules to normalize CROHME 2013 latex notations, since it is used as validation set, it will not affect much. Unlike CROHME 2013, the CROHME 2014 latex notations have been well normalized manually by iFLYTEK company, so we only released the CROHME 2014 dataset. We didn't normalize CROHME 2016 latex notations either, but we don't have to, we can evaluate CROHME 2016 test set by using MathML representations, which are well normalized in raw inkml files.

**Comment by wwjwhen** [comment]
oh, I see! Thanks!

**Comment by LinJM** [comment]
@JianshuZhang  you said: "normalization needs bilinear interpolation, and the average size of each math symbol is normalized to 40 pixels (short length, keeping the ratio of height to width)"

but how can I determine which stroke belongs to the same math symbol，especially in the testing.

**Comment by JianshuZhang** [comment]
About 40 pixels not accurate 40 pixels, you can average the height of all strokes and set the average height to 40

发自我的 iPhone

**Comment by LinJM** [comment]
Can you release the CROHME 2016 test images？ then people can use the same 2016 test image to eval the algorithm.

**Comment by JianshuZhang** [comment]
OK， I will release the 2016 images soon after the ICPR 2018 conference(I am attendimg the conference).

发自我的 iPhone

**Comment by LinJM** [comment]
hello，jianshu，when can you release your 2016 images? I use my own 2016 image to test the model, but it's performance is too bad.

**Comment by JianshuZhang** [comment]
@LinJM Sorry for the delay, the CROHME 2016 image is released now, you may check the difference between the released images and yours.

**Comment by LinJM** [comment]
Thanks. Can you also release the test_caption.txt for CROHME 2016?

**Comment by JianshuZhang** [comment]
As for my caption files of CROHME, they are all manually labeled (need normalization) by iFLYTEK company, I can only release the CROHME 2014 caption file on their agreement. However, for CROHME 2016, it is not necessary to have normalized latex caption file, you can just use the MathML structure in inkml file for evaluation. 



xysszjs@mail.ustc.edu.cn
 
From: Jeremy
Date: 2018-08-27 19:00
To: JianshuZhang/WAP
CC: Jianshu Zhang; Mention
Subject: Re: [JianshuZhang/WAP] Question about validation set (#8)
Thanks. Can you also release the test_caption.txt for CROHME 2016?
